# Generated by Django 5.0.4 on 2024-04-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_alter_artikel_options_alter_kategori_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '3. Sumber',
            },
        ),
    ]
