# Generated by Django 5.0.4 on 2024-04-25 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_sumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SosialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=255)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='berita.artikel')),
            ],
            options={
                'verbose_name_plural': '3. SosialMedia',
            },
        ),
        migrations.DeleteModel(
            name='Sumber',
        ),
    ]
