# Generated by Django 5.0.4 on 2024-04-25 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_sosialmedia_delete_sumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosialmedia',
            options={'verbose_name_plural': '3. Sosoal Media'},
        ),
        migrations.RenameField(
            model_name='sosialmedia',
            old_name='facebook',
            new_name='Sumber',
        ),
        migrations.RemoveField(
            model_name='sosialmedia',
            name='username',
        ),
        migrations.AddField(
            model_name='sosialmedia',
            name='judul',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='berita.artikel'),
        ),
    ]
