# Generated by Django 5.0.4 on 2024-04-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0005_alter_sosialmedia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosialmedia',
            options={'verbose_name_plural': '3. Sosial Media'},
        ),
    ]
