# Generated by Django 5.0.4 on 2024-04-25 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0006_alter_sosialmedia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosialmedia',
            name='judul',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='berita.artikel'),
        ),
    ]
