# Generated by Django 5.0.4 on 2024-05-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0007_alter_sosialmedia_judul'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SosialMedia',
        ),
    ]
