# Generated by Django 5.0.4 on 2024-05-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0008_delete_sosialmedia'),
        ('berita', '0009_artikel_created_at'),
    ]

    operations = [
    ]
