# Generated by Django 5.0.4 on 2024-05-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0011_artikel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='slug',
        ),
    ]
