# Generated by Django 5.0.4 on 2024-05-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0012_remove_artikel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='sosialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
            ],
        ),
    ]
