# Generated by Django 5.0.4 on 2024-05-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0013_sosialmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sosialmedia',
        ),
    ]
